### ISSUE TITLE
doesn't work on macOS 

### ISSUE THREAD

**Issue by noname122021** [ashipunov/img2djvu#3]
run script like:
`$ ./img2djvu -l 1 out`
result is 

```
$
Folder name is required.
Usage: "img2djvu" [options] relative_folder_name

Options:
 -a ...
```

so I fix it by modifying script and run it like this
`$ ./img2djvu -l 1 -- out`
attach working version
[img2djvu.zip](https://github.com/ashipunov/img2djvu/files/532155/img2djvu.zip)

**Comment by ashipunov** [comment]
Could you please explain more? What exactly is a problem? Is it that getopt on macOS is not a GNU getopt?

**Comment by noname122021** [comment]
by default on macOS "getopt" not installed

**Comment by ashipunov** [comment]
What will happen if you install GNU getopt? Will img2djvu work without modification?

**Comment by noname122021** [comment]
You was right, on macOS by default installed "BSD" version of "getopt", I install "gnu-getopt" by "brew", write the path of it /usr/local/Cellar/gnu-getopt/1.1.6/bin/ to my PATH at first place
`PATH=/usr/local/Cellar/gnu-getopt/1.1.6/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
   and it works

**Comment by ashipunov** [comment]
OK, thank you.
